** Summit Dub Squad, Flagstaff, AZ, USA 2020-present, bari sax

- Full concert at Orpheum in Flagstaff,
  https://www.youtube.com/watch?v=eSm3QJ4dIMU&feature=youtu.be&t=3620

** F-Town Sound, Flagstaff, AZ, USA 2018-present, bari sax

- Web site with photos/videos/booking info: https://ftownsound.com/
- Crystal Frontier at Flagstaff Foundry, Jan 2019
  https://www.youtube.com/watch?v=LxTmlZe7oUY (bari sax solo)
- Full concert at Orpheum in Flagstaff, June 6 2020
  https://www.youtube.com/watch?v=9ot5kbVyyIQ

** The Van Hornies, Montreal, QC, Canada 2016-2018, bari sax

- We Got That Fire, winter residence live recording session,
  https://www.youtube.com/watch?v=LuKkk0Qfb7M (bari sax solo)

** choeur solis, Montreal, QC, Canada 2015-2016, voice (tenor/bass)

Villeray community choir, we practiced and performed in the Sainte
Cécile church.  http://choeursolis.com/

** brass mob, Montreal, QC, Canada 2014-2015, clarinet and bari sax

- various tunes live at L'escalier, 28 Mar 2015
  https://www.youtube.com/watch?v=fHutz5qTZj8
- Sexual Feeling live at Pub St-Denis, 22 Mar 2015
  https://www.youtube.com/watch?v=kr7ND1Yary4


** Balkansambl, Paris, France 2010-2011, alto sax

http://www.balkansambl.fr/ There were several formations by this name,
all directed by bandleader José Ponzone. Repertoire: eastern european
/ balkan brass band tunes.

** La RFF, Paris, France 2009-2012, alto and bari sax

http://therff.free.fr/ The official brass band (fanfare) of [[https://www.minesparis.psl.eu/][Mines
ParisTech]], which was one of my academic affiliations during my
PhD. Unlike the other fanfares I played with, this one is mostly
composed of current students of the school (and some alumni). This
fanfare has a repertoire of "saucisson" songs which means "sausage"
(songs that everybody knows/plays). I went on several fun train trips
with this band, including to Toulouse, Montpellier, and [[https://en.wikipedia.org/wiki/Saint-Jean-de-Luz][St-Jean-de-Luz]]
for the Tuna Festival.

** Les Fines Pôlettes, Paris, France 2009-2012, alto and bari sax

https://finespolettes.bandcamp.com/ A French brass band (fanfare)
which was originally formed from students of the [[https://www.ensad.fr/][Ecole Nationale
Superiere des Arts Decoratifs (ENSAD)]]. After graduation the fanfare
kept playing together, and recruited several musicians from outside of
the ENSAD. (including me!) Repertoire: latin/swing/groove, mainly
composed by the souba (sousaphone) player Mathieu Choinet, who went on
to play with [[http://grizz-li.com/][Grizz-Li]] and [[https://balaphonics.bandcamp.com/music][Balaphonics]].
- live performances at Altitude jazz festival, serre-chevalier ski
  resort, Hautes-Alpes, France, 2011
  - It Don't Mean A Thing if You Ain't Got That Swing,
    https://www.youtube.com/watch?v=AAR7gYknLaM (small alto sax solo)
  - Feria while skiing down the bunny hill,
    https://www.dailymotion.com/video/xh9se3 (call/response alto sax
    solo with Sophie Raynal on trombone)
  - Pepère at Les Grands Bains de Monetier, Monetier-les-bains,
    https://www.dailymotion.com/video/xhc8xa (call/response alto sax
    solo with Sophie Raynal trombone)
- Manisero at residence in France
  https://www.youtube.com/watch?v=aYw0Mh0RQwY
- O Toi Mon Bel Amour concert at Studio d'Ermitage, 21 Jan 2012
  https://www.youtube.com/watch?v=oB_XBVBGBQk
- Sauce in public in Paris, Quai St-Michel, 19 Mar 2012
  https://www.youtube.com/watch?v=54ldksukLRw
- Fat City Strut at Nova Lapa Jazz fest, Rio de Janeiro, Brazil, Mar
  2012 https://www.youtube.com/watch?v=7CKXmVhdq9M (bari sax solo)
- It Don't Mean A Thing in front of a metro station, Rio de Janeiro,
  Brazil, Apr 2012 https://www.youtube.com/watch?v=NJI08G7g7xM (bari
  sax solo)

** Shtarak Nikov, Paris, France, 2008-2009, alto sax

This band was my introduction to the world of [[https://fr.wikipedia.org/wiki/Fanfare_des_Beaux-Arts][French brass bands
(fanfares)]], which is very different from the American tradition. One
difference is that the French fanfares are much smaller (10-20
musicians) than the American university marching bands (100-200
musicians). In some of the [[https://fr.wikipedia.org/wiki/Grande_%C3%A9cole][Grande Ecoles]], a new French brass band is
formed each year among Freshmen, who typically do not have any prior
musical experience, so learning new songs takes a while as they must
learn their instruments and learn the songs by ear at the same time
(typically sheet music is not used). This band practiced at the [[https://www.ensad.fr/][Ecole
Nationale Superiere des Arts Decoratifs (ENSAD)]], and notable
performances include a battle of the ENSAD brass bands at the [[http://www.cabaretsauvage.com/][Cabaret
Sauvage]] (Spring 2009?), and opening for The Slackers at Université
Paris IX Dauphine (May 2009).

** Brass Liberation Orchestra, San Francisco, CA, USA 2007-2008, alto sax

Repertoire: eclectic, afrobeat / eastern european / etc.
- HONK brass band festival in Boston, MA, Bubamara with What Cheer Brigade
  https://www.youtube.com/watch?v=setJCfGPDgA
- Benefit concert in Dolores Park, SF, various songs
  https://www.youtube.com/watch?v=yBSS-LHQ5_4

** KANTAR, Berkeley, CA, 2004-2005, alto sax

This was a 6-piece funk/rock band with some fine musicians who have
gone on to do some interesting projects
- [[http://ruthiedineen.com/][Ruthie Dineen]] keyboard
- [[http://www.owlbrotherhood.net/][Alex Baechle]] guitar

** West Grand Blvd, East Bay, CA, 2003-2004, alto sax

A 6-piece soul/motown band that is apparently still around as of 2019,
https://westgrandblvd.wordpress.com/

** Cal Band, Berkeley, CA, USA 2002-2006, alto sax

Lots of videos on youtube, like the popular [[https://www.youtube.com/watch?v=H2-TDOUng4E][Bounce with Me show]] from
Fall 2004.

** Santa Ana Winds, CA, USA, 2000-2001, clarinet

https://en.wikipedia.org/wiki/Santa_Ana_Winds_Youth_Band

** Foothill High School Bands, Tustin, CA, USA, 1998-2001, clarinet

Went on tour for a week in Hawaii in 2001 with my high school band!
